[[redirects]]
  from = "/proxy/*"
  to = "https://unipass.customs.go.kr:38010/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/proxy/*"
  to = "https://www.koreaexim.go.kr/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/proxy/*"
  to = "http://fx.kebhana.com/:splat"
  status = 200
  force = true